### ISSUE TITLE
Have LazyValueMap keep insert order

### ISSUE THREAD

**Issue by slandelle** [advantageous/boon#12]
I know that the JSON spec doesn't guarantee attributes order, but in practice, browsers do.
And so does Jackson.

`LazyMap` indeed stores internally in a `LinkedHashMap`, so order is preserved.
But `LazyValueMap` uses a regular `HashMap`.

Would you consider either aligning, or add an option? I can provide a PR as soon as #11 gets merged (would conflict otherwise).

**Comment by RichardHightower** [comment]
I look forward to your pull request. 
Somehow email notification is turned off for this. 
Sorry it took so long to respond.

**Comment by slandelle** [comment]
Done :)

**Comment by slandelle** [comment]
Glad you're still around!
