### ISSUE TITLE
Unneccesary Java 8 dependency?

### ISSUE THREAD

**Issue by Osndok** [advantageous/boon#3]
Hi,

It appears that the source/target version is not specified in the pom.xml file, and a dependency on Java 8 byte code version is introduced by the machine that creates the jar files (that find their way to Maven Central).

This caused some issues for me at runtime, and thought you might want to know that your library might be more useful to others in Maven Central if you specifically target java 7 (or 6?) in the pom file.

**Comment by RichardHightower** [comment]
We rely on Java 8 features. 
Use boon from the boon project if you want Java 7 support. 

https://github.com/boonproject/boon

It also has more docs.
